trigger:
  branches:
    include:
      - develop
  paths:
    exclude:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'tpfinal-vars'
  - name: frontProjectPath
    value: 'mon-app'

jobs:
  - job: Front
    steps:
      - template: ./templates/_build-front.yml
